### ISSUE TITLE
Offline testing

### ISSUE THREAD

**Issue by jayvdb** [jantman/versionfinder#9]
I assume that the tests can be run offline based on https://github.com/jantman/versionfinder#acceptance-tests and the use of pytest-blockage.

However it looks like the test runner is doing the network fetches before doing the tests, and storing them in a tempdir.

I am attempting to package this for openSUSE, so the builds are occurring in a VM isolated from the network.  I need to download any needed test data and upload them into the VM before the build commences.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-versionfinder

For this to work, I suspect the test runner logic needs an enhancement to detect and use pre-existing files.  Instructions to achieve this would be helpful for other distro packagers.

**Comment by jantman** [comment]
@jayvdb Apologies for the delayed response to this.

No, the tests cannot be run offline. The unit test suite uses pytest-blockage to ensure that no network tests are made during the unit test runs, but the acceptance tests require network access - and that's pretty much central to the purpose of the acceptance tests.

The issue here isn't the test runner... it's that the acceptance tests literally run ``pip install`` against various git URLs as well as sdist and wheel packages. As far as I know, there's no real way to pre-download that, and if there was, I think it would negate the purpose of the acceptance tests.

I suppose that the "real" fix here would be for me to split the acceptance test suite into two separate groups, one that can function without network access and one that requires network access. However, as far as I know (and as far as [libraries.io knows](https://libraries.io/pypi/versionfinder/dependents)), this package is only used by one other package in the world - my awslimitchecker package. And to be honest, if you're packaging awslimitchecker for a distro, versionchecker is pretty much pointless since you'll likely only be packaging a release version.

If there's no way to get openSUSE packages built with network access (which seems like a pretty poor limitation to me, but I'm sure they have their reasons), my recommendation would be to just not run the acceptance tests at all. Most of versionfinder is pointless if you're running awslimitchecker from an OS package anyway.

**Comment by jayvdb** [comment]
I was planning on using versionfinder in a new tool i'm building, which is to be used on non-OS-packaged code.
For the moment I'll disable the relevant tests, but I'll also take a stab at getting more of them working using offline pre-fetched data.

**Comment by jantman** [comment]
Not sure if anything happened with this, but I'm closing it due to age. @jayvdb if you ever did any work on this, I'd be happy to merge it, but as-is I'm only using this in a handful of packages.
